// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_zs0SVwUYnHGuHm_JkRtNACWxNs_GuEM',
    appId: '1:553750875272:web:cc5850327a1e49cf4aa33d',
    messagingSenderId: '553750875272',
    projectId: 'clippy-indie',
    authDomain: 'clippy-indie.firebaseapp.com',
    storageBucket: 'clippy-indie.appspot.com',
    measurementId: 'G-X1WZPBRCJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqpgV3htuCy-4wsqfiJ-TF75SLhi1l_1A',
    appId: '1:553750875272:android:435f3847dc4815fd4aa33d',
    messagingSenderId: '553750875272',
    projectId: 'clippy-indie',
    storageBucket: 'clippy-indie.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhYNYNMLC3f4bkg-5PCGUjUIZO5-capng',
    appId: '1:553750875272:ios:89743d98c524813b4aa33d',
    messagingSenderId: '553750875272',
    projectId: 'clippy-indie',
    storageBucket: 'clippy-indie.appspot.com',
    androidClientId: '553750875272-85edectvcrvatngc3n5a9a80sunels84.apps.googleusercontent.com',
    iosClientId: '553750875272-9qk8keed8fjmhes9qget3n67ijmrg0mb.apps.googleusercontent.com',
    iosBundleId: 'com.infamousindie.clippy.clippy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhYNYNMLC3f4bkg-5PCGUjUIZO5-capng',
    appId: '1:553750875272:ios:89743d98c524813b4aa33d',
    messagingSenderId: '553750875272',
    projectId: 'clippy-indie',
    storageBucket: 'clippy-indie.appspot.com',
    androidClientId: '553750875272-85edectvcrvatngc3n5a9a80sunels84.apps.googleusercontent.com',
    iosClientId: '553750875272-9qk8keed8fjmhes9qget3n67ijmrg0mb.apps.googleusercontent.com',
    iosBundleId: 'com.infamousindie.clippy.clippy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_zs0SVwUYnHGuHm_JkRtNACWxNs_GuEM',
    appId: '1:553750875272:web:3782636eda9615904aa33d',
    messagingSenderId: '553750875272',
    projectId: 'clippy-indie',
    authDomain: 'clippy-indie.firebaseapp.com',
    storageBucket: 'clippy-indie.appspot.com',
    measurementId: 'G-TM46V6V9NW',
  );

}